### ISSUE TITLE
Implement 'Edit Year'

### ISSUE THREAD

**Issue by chenaaron3** [icssc/peterportal-client#95]
- [x] When click on edit year, should prompt user for a new year.
- [x] After submitting, should display new year.
- [x] Check if year already exists for duplicate
- [x] Ensure years are also sorted
